import Head from "next/head";
import HomePage from "./HomePage";
import Default from "@/components/layouts/Default/Default";
import Login from "./Login";
import { useSession } from "next-auth/react";

type Props = {
	children: React.ReactNode;
};

export default function Home() {
	const session = useSession();
	const authenticated = "authenticated";

	return (
		<>
			<Head>
				<title>Spotify Clone!</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			{session.status === authenticated ? (
				<Default>
					<HomePage session={session} />
				</Default>
			) : (
				<Login session={session} />
			)}

			{/* <div>Music Player</div> */}
		</>
	);
}
