import Head from 'next/head';
import Image from 'next/image';
import HomePage from './HomePage';
import Default from '@/components/layouts/Default/Default';
import { SessionProvider } from 'next-auth/react';

type Props = {
	children: React.ReactNode;
};

export default function Home() {
	return (
		<>
			<Head>
				<title>Spotify Clone!</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Default>
				<HomePage />
			</Default>

			{/* <div>Music Player</div> */}
		</>
	);
}
